const STORAGE_KEY = "numeronautas_robo";

const baseMap = [
  "##########",
  "#P..D.C.G#",
  "#.##.##..#",
  "#..C...#.#",
  "##.###E..#",
  "#..E..D..#",
  "#...##...#",
  "##########",
];

const maps = [
  baseMap,
  [
    "##########",
    "#P.C..D.G#",
    "#.##.##..#",
    "#..E.C.#.#",
    "##.###D..#",
    "#..C..E..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.D..C.G#",
    "#..#.##..#",
    "##.E...#.#",
    "#..###D..#",
    "#.C..E...#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P..E.C.G#",
    "#.##.##D.#",
    "#..C...#.#",
    "##.###E..#",
    "#..D..C..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.C.E..G#",
    "#.##.##D.#",
    "#..D...#.#",
    "##.###C..#",
    "#..E..D..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.E.DC.G#",
    "#.##.##..#",
    "#..C...#.#",
    "##.###E..#",
    "#..D..C..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.D.EC.G#",
    "#.##.##..#",
    "#..E...#.#",
    "##.###C..#",
    "#..D..E..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.ECD..G#",
    "#.##.##E.#",
    "#..C...#.#",
    "##.###D..#",
    "#..E..C..#",
    "#...##...#",
    "##########",
  ],
];

const levels = [
  {
    id: 1,
    title: "Bahia de Sumas",
    type: "add",
    icon: "+",
    intro: "Ayuda a Robo a contar grupos de mini robots en el laboratorio.",
    label: "Mision de sumas",
    task: "Junta cantidades",
  },
  {
    id: 2,
    title: "Operacion Resta",
    type: "subtract",
    icon: "-",
    intro: "Robo entra a Operacion Resta, una arena futurista donde cada respuesta correcta dispara un ataque brillante.",
    label: "Mision de restas",
    task: "Derrota con restas",
  },
  {
    id: 3,
    title: "Numeronautas: Laboratorio de Clones",
    type: "multiply",
    icon: "x",
    intro: "Ayuda a Robo a restaurar un laboratorio futurista creando clones con multiplicaciones.",
    label: "Mision de multiplicacion",
    task: "Crea clones",
  },
  {
    id: 4,
    title: "Isla Divisora",
    type: "divide",
    icon: "/",
    intro: "Divide energia en partes iguales para estabilizar la isla.",
    label: "Mision de division",
    task: "Reparte cantidades",
  },
  {
    id: 5,
    title: "Circuito Relampago",
    type: "mixed",
    icon: "+-",
    intro: "Combina suma y resta antes de que se cierre el circuito.",
    label: "Mision mixta",
    task: "Suma y resta",
    pool: ["add", "subtract"],
  },
  {
    id: 6,
    title: "Fabrica de Patrones",
    type: "mixed",
    icon: "x/",
    intro: "Alterna multiplicaciones y divisiones para ordenar la fabrica.",
    label: "Mision de patrones",
    task: "Multiplica y divide",
    pool: ["multiply", "divide"],
  },
  {
    id: 7,
    title: "Laberinto Numeral",
    type: "mixed",
    icon: "?",
    intro: "Usa todas las operaciones para guiar a Robo por el laberinto.",
    label: "Mision combinada",
    task: "Resuelve de todo",
  },
  {
    id: 8,
    title: "Portal Maestro",
    type: "mixed",
    icon: "*",
    intro: "El reto final mezcla todo lo aprendido para abrir el gran portal.",
    label: "Reto maestro",
    task: "Domina el portal",
  },
];

const conceptByType = {
  add: {
    title: "Sumar es juntar",
    intro: "Cuando sumamos, unimos dos grupos de baterias para saber cuanta energia hay en total.",
    note: "Ejemplo: 2 baterias + 3 baterias = 5 baterias de energia.",
    demo: [
      ["batteries", 2],
      ["symbol", "+"],
      ["batteries", 3],
      ["symbol", "="],
      ["batteryTotal", 5],
    ],
  },
  subtract: {
    title: "Restar es quitar y contar lo que queda",
    intro: "Cuando restamos, empezamos con una cantidad. Luego quitamos, usamos o perdemos una parte. El resultado nos dice cuanto queda.",
    note: "Ejemplo: Robo tenia 9 cargas. Uso 4 cargas en su ataque. Le quedaron 5 cargas.",
    demo: [
      ["battleDots", 9, 4, "9"],
      ["symbol", "-"],
      ["used", 4, "4"],
      ["symbol", "="],
      ["battleDots", 5, 0, "5"],
    ],
  },
  multiply: {
    title: "Multiplicar es crear grupos iguales",
    intro: "En el laboratorio, Robo usa la multiplicacion para crear varios grupos iguales de clones.",
    note: "Ejemplo: 3 capsulas crean 4 clones cada una. 3 x 4 = 12 clones.",
    demo: [
      ["total", "3"],
      ["symbol", "x"],
      ["total", "4"],
      ["symbol", "="],
      ["total", "12"],
    ],
  },
  divide: {
    title: "Dividir es repartir",
    intro: "Cuando dividimos, repartimos una cantidad en partes iguales.",
    note: "Ejemplo: 12 baterias / 3 estaciones = 4 baterias por estacion.",
    demo: [
      ["total", "12"],
      ["symbol", "/"],
      ["total", "3"],
      ["symbol", "="],
      ["total", "4"],
    ],
  },
  mixed: {
    title: "Elige la herramienta correcta",
    intro: "En las misiones mixtas puede aparecer cualquier operacion. Mira bien el simbolo antes de responder.",
    note: "Consejo: primero identifica si debes juntar, quitar, repetir grupos o repartir.",
    demo: [
      ["total", "+"],
      ["symbol", "-"],
      ["total", "x"],
      ["symbol", "/"],
      ["total", "?"],
    ],
  },
};
