const STORAGE_KEY = "numeronautas_robo";

const baseMap = [
  "##########",
  "#P..D.C.G#",
  "#.##.##..#",
  "#..C...#.#",
  "##.###E..#",
  "#..E..D..#",
  "#...##...#",
  "##########",
];

const maps = [
  baseMap,
  [
    "##########",
    "#P.C..D.G#",
    "#.##.##..#",
    "#..E.C.#.#",
    "##.###D..#",
    "#..C..E..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.D..C.G#",
    "#..#.##..#",
    "##.E...#.#",
    "#..###D..#",
    "#.C..E...#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P..E.C.G#",
    "#.##.##D.#",
    "#..C...#.#",
    "##.###E..#",
    "#..D..C..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.C.E..G#",
    "#.##.##D.#",
    "#..D...#.#",
    "##.###C..#",
    "#..E..D..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.E.DC.G#",
    "#.##.##..#",
    "#..C...#.#",
    "##.###E..#",
    "#..D..C..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.D.EC.G#",
    "#.##.##..#",
    "#..E...#.#",
    "##.###C..#",
    "#..D..E..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.ECD..G#",
    "#.##.##E.#",
    "#..C...#.#",
    "##.###D..#",
    "#..E..C..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.C.D.EG#",
    "#.##..#..#",
    "#..E.C#..#",
    "##.##..D.#",
    "#..C.E...#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.E..D.G#",
    "#..##.#..#",
    "#.C..E...#",
    "##.##D#..#",
    "#..E..C..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.D.CE.G#",
    "#.##.##..#",
    "#..E..C#.#",
    "##..##D..#",
    "#.C..E...#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.E.CD.G#",
    "#..#.##..#",
    "##.C.E#..#",
    "#..##.D..#",
    "#.E..C...#",
    "#...##...#",
    "##########",
  ],
];

const levels = [
  {
    id: 1,
    title: "Bahia de Sumas",
    type: "add",
    icon: "+",
    intro: "Ayuda a Robo a contar grupos de mini robots en el laboratorio.",
    label: "Mision de sumas",
    task: "Junta cantidades",
  },
  {
    id: 2,
    title: "Operacion Resta",
    type: "subtract",
    icon: "-",
    intro: "Robo entra a Operacion Resta, una arena futurista donde cada respuesta correcta dispara un ataque brillante.",
    label: "Mision de restas",
    task: "Derrota con restas",
  },
  {
    id: 3,
    title: "Numeronautas: Laboratorio de Clones",
    type: "multiply",
    icon: "x",
    intro: "Ayuda a Robo a restaurar un laboratorio futurista creando clones con multiplicaciones.",
    label: "Mision de multiplicacion",
    task: "Crea clones",
  },
  {
    id: 4,
    title: "ROBO DELIVERY",
    type: "divide",
    icon: "RD",
    intro: "Ayuda a Robo Delivery a repartir paquetes energeticos entre drones y estaciones de la ciudad.",
    label: "Mision de repartos",
    task: "Entrega paquetes",
    concept: {
      title: "Dividir es repartir entregas",
      intro: "Robo Delivery toma un grupo de paquetes y los reparte por igual entre drones repartidores.",
      note: "Ejemplo: 24 paquetes / 6 drones = 4 paquetes para cada drone.",
      demo: [
        ["total", "24"],
        ["symbol", "/"],
        ["total", "6"],
        ["symbol", "="],
        ["total", "4"],
      ],
    },
  },
  {
    id: 5,
    title: "Circuito Relampago",
    type: "mixed",
    icon: "+-",
    intro: "Combina suma y resta antes de que se cierre el circuito.",
    label: "Mision mixta",
    task: "Suma y resta",
    pool: ["add", "subtract"],
  },
  {
    id: 6,
    title: "Fabrica de Patrones",
    type: "mixed",
    icon: "x/",
    intro: "Alterna multiplicaciones y divisiones para ordenar la fabrica.",
    label: "Mision de patrones",
    task: "Multiplica y divide",
    pool: ["multiply", "divide"],
  },
  {
    id: 7,
    title: "Laberinto Numeral",
    type: "mixed",
    icon: "?",
    intro: "Usa todas las operaciones para guiar a Robo por el laberinto.",
    label: "Mision combinada",
    task: "Resuelve de todo",
  },
  {
    id: 8,
    title: "Portal Maestro",
    type: "mixed",
    icon: "*",
    intro: "El reto final mezcla todo lo aprendido para abrir el gran portal.",
    label: "Reto maestro",
    task: "Domina el portal",
  },
  {
    id: 9,
    title: "Nebulosa de Energia",
    type: "mixed",
    icon: "+x",
    intro: "Robo mezcla baterias y grupos repetidos para encender una nebulosa completa.",
    label: "Combo suma x multi",
    task: "Junta y multiplica",
    pool: ["add", "multiply"],
    concept: {
      title: "Combina juntar y repetir",
      intro: "A veces debes sumar energia y otras veces crear grupos iguales. Mira el simbolo antes de tocar la respuesta.",
      note: "Si ves +, junta. Si ves x, cuenta grupos repetidos.",
      demo: [
        ["total", "+"],
        ["symbol", "o"],
        ["total", "x"],
        ["symbol", "="],
        ["total", "?"],
      ],
    },
  },
  {
    id: 10,
    title: "Estacion Prisma",
    type: "mixed",
    icon: "-/",
    intro: "La estacion cambia entre quitar energia y repartir cargas en partes iguales.",
    label: "Combo resta y division",
    task: "Quita y reparte",
    pool: ["subtract", "divide"],
    concept: {
      title: "Quita o reparte",
      intro: "En este reto aparecen restas y divisiones. Primero identifica si Robo debe quitar o repartir.",
      note: "Si ves -, resta lo usado. Si ves /, reparte en grupos iguales.",
      demo: [
        ["total", "-"],
        ["symbol", "o"],
        ["total", "/"],
        ["symbol", "="],
        ["total", "?"],
      ],
    },
  },
  {
    id: 11,
    title: "Orbita Triple",
    type: "mixed",
    icon: "+x/",
    intro: "Tres operaciones giran alrededor del planeta: suma, multiplicacion y division.",
    label: "Combo triple",
    task: "Elige la operacion",
    pool: ["add", "multiply", "divide"],
    concept: {
      title: "Tres herramientas",
      intro: "Cada portal puede pedir juntar, crear grupos iguales o repartir. El simbolo te dice que herramienta usar.",
      note: "Observa con calma: + junta, x repite grupos y / reparte.",
      demo: [
        ["total", "+"],
        ["symbol", "x"],
        ["total", "/"],
        ["symbol", "="],
        ["total", "?"],
      ],
    },
  },
  {
    id: 12,
    title: "Galaxia Combinada",
    type: "mixed",
    icon: "mix",
    intro: "El gran reto combina todas las operaciones para cerrar la aventura de Robo.",
    label: "Combo total",
    task: "Resuelve de todo",
    pool: ["add", "subtract", "multiply", "divide"],
    concept: {
      title: "Todas las operaciones",
      intro: "Este nivel mezcla suma, resta, multiplicacion y division. Tu mision es leer el simbolo y responder rapido.",
      note: "Respira, mira el simbolo y usa la estrategia correcta.",
      demo: [
        ["total", "+"],
        ["symbol", "-"],
        ["total", "x"],
        ["symbol", "/"],
        ["total", "?"],
      ],
    },
  },
];

const conceptByType = {
  add: {
    title: "Sumar es juntar",
    intro: "Cuando sumamos, unimos dos grupos de baterias para saber cuanta energia hay en total.",
    note: "Ejemplo: 2 baterias + 3 baterias = 5 baterias de energia.",
    demo: [
      ["batteries", 2],
      ["symbol", "+"],
      ["batteries", 3],
      ["symbol", "="],
      ["batteryTotal", 5],
    ],
  },
  subtract: {
    title: "Restar es quitar y contar lo que queda",
    intro: "Cuando restamos, empezamos con una cantidad. Luego quitamos, usamos o perdemos una parte. El resultado nos dice cuanto queda.",
    note: "Ejemplo: Robo tenia 9 cargas. Uso 4 cargas en su ataque. Le quedaron 5 cargas.",
    demo: [
      ["battleDots", 9, 4, "9"],
      ["symbol", "-"],
      ["used", 4, "4"],
      ["symbol", "="],
      ["battleDots", 5, 0, "5"],
    ],
  },
  multiply: {
    title: "Multiplicar es crear grupos iguales",
    intro: "En el laboratorio, Robo usa la multiplicacion para crear varios grupos iguales de clones.",
    note: "Ejemplo: 3 capsulas crean 4 clones cada una. 3 x 4 = 12 clones.",
    demo: [
      ["total", "3"],
      ["symbol", "x"],
      ["total", "4"],
      ["symbol", "="],
      ["total", "12"],
    ],
  },
  divide: {
    title: "Dividir es repartir",
    intro: "Cuando dividimos, repartimos una cantidad en partes iguales.",
    note: "Ejemplo: 12 baterias / 3 estaciones = 4 baterias por estacion.",
    demo: [
      ["total", "12"],
      ["symbol", "/"],
      ["total", "3"],
      ["symbol", "="],
      ["total", "4"],
    ],
  },
  mixed: {
    title: "Elige la herramienta correcta",
    intro: "En las misiones mixtas puede aparecer cualquier operacion. Mira bien el simbolo antes de responder.",
    note: "Consejo: primero identifica si debes juntar, quitar, repetir grupos o repartir.",
    demo: [
      ["total", "+"],
      ["symbol", "-"],
      ["total", "x"],
      ["symbol", "/"],
      ["total", "?"],
    ],
  },
};
