const STORAGE_KEY = "robomaticas_robo";

const baseMap = [
  "##########",
  "#P..D.C.G#",
  "#.##.##..#",
  "#..C...#.#",
  "##.###E..#",
  "#..E..D..#",
  "#...##...#",
  "##########",
];

const maps = [
  baseMap,
  [
    "##########",
    "#P.C..D.G#",
    "#.##.##..#",
    "#..E.C.#.#",
    "##.###D..#",
    "#..C..E..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.D..C.G#",
    "#..#.##..#",
    "##.E...#.#",
    "#..###D..#",
    "#.C..E...#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P..E.C.G#",
    "#.##.##D.#",
    "#..C...#.#",
    "##.###E..#",
    "#..D..C..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.C.E..G#",
    "#.##.##D.#",
    "#..D...#.#",
    "##.###C..#",
    "#..E..D..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.E.DC.G#",
    "#.##.##..#",
    "#..C...#.#",
    "##.###E..#",
    "#..D..C..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.D.EC.G#",
    "#.##.##..#",
    "#..E...#.#",
    "##.###C..#",
    "#..D..E..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.ECD..G#",
    "#.##.##E.#",
    "#..C...#.#",
    "##.###D..#",
    "#..E..C..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.C.D.EG#",
    "#.##..#..#",
    "#..E.C#..#",
    "##.##..D.#",
    "#..C.E...#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.E..D.G#",
    "#..##.#..#",
    "#.C..E...#",
    "##.##D#..#",
    "#..E..C..#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.D.CE.G#",
    "#.##.##..#",
    "#..E..C#.#",
    "##..##D..#",
    "#.C..E...#",
    "#...##...#",
    "##########",
  ],
  [
    "##########",
    "#P.E.CD.G#",
    "#..#.##..#",
    "##.C.E#..#",
    "#..##.D..#",
    "#.E..C...#",
    "#...##...#",
    "##########",
  ],
];

const levels = [
  {
    id: 1,
    title: "Bahía de Sumas",
    type: "add",
    icon: "+",
    intro: "Acompaña a Robo a cargar la Bahía de Sumas conectando baterías.",
    label: "Mision de sumas",
    task: "Junta cantidades",
    concept: {
      title: "Sumar es cargar el núcleo",
      intro: "En Bahía de Sumas, Robo conecta dos grupos de baterías. Al juntarlas, el núcleo recibe una sola carga total.",
      note: "Ejemplo: 2 baterías + 3 baterías = 5 baterías conectadas al núcleo.",
      demo: [
        ["batteries", 2],
        ["symbol", "+"],
        ["batteries", 3],
        ["symbol", "="],
        ["batteryTotal", 5],
      ],
    },
  },
  {
    id: 2,
    title: "Operacion Resta",
    type: "subtract",
    icon: "-",
    intro: "Robo entra a Operacion Resta, una arena futurista donde cada respuesta correcta dispara un ataque brillante.",
    label: "Mision de restas",
    task: "Derrota con restas",
    concept: {
      title: "Restar es quitar energia",
      intro: "En la arena, Robo empieza con una cantidad de carga y gasta una parte al atacar.",
      note: "Ejemplo: Robo tenía 9 cargas. Uso 4 en un laser. Le quedaron 5 cargas.",
      demo: [
        ["battleDots", 9, 4, "9"],
        ["symbol", "-"],
        ["used", 4, "4"],
        ["symbol", "="],
        ["battleDots", 5, 0, "5"],
      ],
    },
  },
  {
    id: 3,
    title: "Planeta Clonix",
    type: "multiply",
    icon: "x",
    intro: "Acompaña a Robo a restaurar un laboratorio futurista creando clones con multiplicaciones.",
    label: "Mision de multiplicacion",
    task: "Crea clones",
    concept: {
      title: "Multiplicar es crear grupos iguales",
      intro: "En Planeta Clonix, cada portal crea la misma cantidad de criaturas. Multiplicar cuenta todos los clones juntos.",
      note: "Ejemplo: 3 portales crean 4 clones cada uno. 3 x 4 = 12 clones.",
      demo: [
        ["total", "3"],
        ["symbol", "x"],
        ["total", "4"],
        ["symbol", "="],
        ["total", "12"],
      ],
    },
  },
  {
    id: 4,
    title: "CENTRAL DELIVERY",
    type: "divide",
    icon: "RD",
    intro: "Ayuda a Central Delivery a repartir paquetes energeticos entre drones y estaciones de la ciudad.",
    label: "Mision de repartos",
    task: "Entrega paquetes",
    concept: {
      title: "Dividir es repartir entregas",
      intro: "Central Delivery toma un grupo de paquetes y los reparte por igual entre drones repartidores.",
      note: "Ejemplo: 24 paquetes / 6 drones = 4 paquetes para cada drone.",
      demo: [
        ["total", "24"],
        ["symbol", "/"],
        ["total", "6"],
        ["symbol", "="],
        ["total", "4"],
      ],
    },
  },
  {
    id: 5,
    title: "Torre de Compuertas",
    type: "mixed",
    mode: "energyLab",
    icon: "+-",
    intro: "Acompaña a Robo a despertar una torre de compuertas: unas puertas cargan energia y otras liberan el exceso antes de que tiemble el sistema.",
    label: "Operaciones combinadas",
    task: "Cuenta capsulas",
    pool: ["add", "subtract"],
    concept: {
      title: "Las capsulas entran y salen",
      intro: "En la torre, primero miras cuantas capsulas hay. Cuando aparece una suma, entran capsulas nuevas. Cuando aparece una resta, algunas salen del reactor.",
      note: "Ejemplo: 6 + 2 - 1. Empiezas con 6, entran 2 y ves 8. Luego sale 1 y quedan 7.",
      demo: [
        ["batteryTotal", 5],
        ["symbol", "+"],
        ["batteryTotal", 3],
        ["symbol", "-"],
        ["batteryTotal", 2],
        ["symbol", "="],
        ["batteryTotal", 6],
      ],
    },
  },
  {
    id: 6,
    title: "Fabrica Chispa",
    type: "mixed",
    mode: "energyLab",
    icon: "-x",
    intro: "Acompaña a Robo a rescatar la Fabrica Chispa: los brazos fabrican piezas en grupos y la banda consume recursos al instalarlas.",
    label: "Resta + multiplicacion",
    task: "Repara maquinas",
    pool: ["subtract", "multiply"],
    concept: {
      title: "Primero fabrica piezas",
      intro: "En Fabrica Chispa, la multiplicacion activa brazos mecanicos que producen tandas iguales. Luego la resta marca cuantos recursos se gastaron en la reparacion.",
      note: "Ejemplo: 10 - 2 x 3. Primero dos brazos hacen 3 piezas cada uno: 6 piezas. Luego se gastan 6 recursos y quedan 4.",
      demo: [
        ["total", "10"],
        ["symbol", "-"],
        ["total", "2"],
        ["symbol", "x"],
        ["total", "3"],
      ],
    },
  },
  {
    id: 7,
    title: "Motor Portal Orion",
    type: "mixed",
    mode: "energyLab",
    icon: "x/",
    intro: "Acompaña a Robo a abrir el Portal Orion: el nucleo multiplica combustible y despues lo divide entre motores de salto.",
    label: "Multiplicacion + division",
    task: "Activa el motor",
    pool: ["multiply", "divide"],
    concept: {
      title: "Genera y distribuye combustible",
      intro: "El Portal Orion multiplica celdas de combustible para cargar el anillo. Luego la division reparte esa carga entre motores.",
      note: "Ejemplo: 4 x 6 / 2. Primero el nucleo crea 24 cargas. Luego las reparte entre 2 motores: 12 por motor.",
      demo: [
        ["total", "4"],
        ["symbol", "x"],
        ["total", "6"],
        ["symbol", "/"],
        ["total", "2"],
      ],
    },
  },
  {
    id: 8,
    title: "Laboratorio Prisma",
    type: "mixed",
    mode: "energyLab",
    icon: "/+",
    intro: "Acompaña a Robo a preparar una mezcla prisma: reparte muestras en tubos iguales y despues suma potencia al reactor.",
    label: "Division + suma",
    task: "Equilibra laboratorio",
    pool: ["divide", "add"],
    concept: {
      title: "Primero reparte, luego potencia",
      intro: "En el Laboratorio Prisma, la division reparte muestras entre tubos iguales. Luego la suma agrega chispas de potencia al reactor final.",
      note: "Ejemplo: 12 / 3 + 4. Primero cada tubo recibe 4 muestras. Luego se agregan 4 chispas y el reactor llega a 8.",
      demo: [
        ["total", "12"],
        ["symbol", "/"],
        ["total", "3"],
        ["symbol", "+"],
        ["total", "4"],
      ],
    },
  },
];

const conceptByType = {
  add: {
    title: "Sumar es cargar el núcleo",
    intro: "Cuando sumamos, conectamos dos grupos de baterías para formar una sola carga total.",
    note: "Ejemplo: 2 baterías + 3 baterías = 5 baterías conectadas al núcleo.",
    demo: [
      ["batteries", 2],
      ["symbol", "+"],
      ["batteries", 3],
      ["symbol", "="],
      ["batteryTotal", 5],
    ],
  },
  subtract: {
    title: "Restar es quitar y contar lo que queda",
    intro: "Cuando restamos, empezamos con una cantidad. Luego quitamos, usamos o perdemos una parte. El resultado nos dice cuanto queda.",
    note: "Ejemplo: Robo tenía 9 cargas. Uso 4 cargas en su ataque. Le quedaron 5 cargas.",
    demo: [
      ["battleDots", 9, 4, "9"],
      ["symbol", "-"],
      ["used", 4, "4"],
      ["symbol", "="],
      ["battleDots", 5, 0, "5"],
    ],
  },
  multiply: {
    title: "Multiplicar es crear grupos iguales",
    intro: "En el laboratorio, Robo usa la multiplicacion para crear varios grupos iguales de clones.",
    note: "Ejemplo: 3 capsulas crean 4 clones cada una. 3 x 4 = 12 clones.",
    demo: [
      ["total", "3"],
      ["symbol", "x"],
      ["total", "4"],
      ["symbol", "="],
      ["total", "12"],
    ],
  },
  divide: {
    title: "Dividir es repartir",
    intro: "Cuando dividimos, repartimos una cantidad en partes iguales.",
    note: "Ejemplo: 12 baterias / 3 estaciones = 4 baterias por estacion.",
    demo: [
      ["total", "12"],
      ["symbol", "/"],
      ["total", "3"],
      ["symbol", "="],
      ["total", "4"],
    ],
  },
  mixed: {
    title: "Elige la herramienta correcta",
    intro: "En las misiones mixtas puede aparecer cualquier operacion. Mira bien el simbolo antes de responder.",
    note: "Consejo: primero identifica si debes juntar, quitar, repetir grupos o repartir.",
    demo: [
      ["total", "+"],
      ["symbol", "-"],
      ["total", "x"],
      ["symbol", "/"],
      ["total", "?"],
    ],
  },
};
